language: php

os:
  - linux

dist: bionic

services:
  - mysql

addons:
  postgresql: "9.6"
  firefox: "47.0.1"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.3

env:
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=master

jobs:
  include:
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 14.2.0
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phpunit --coverage-text --coverage-clover
  - moodle-plugin-ci behat
  - moodle-plugin-ci behat --dump /home/travis/build/moodle/blocks/admin_bookmarks
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt || true
  - /home/travis/build/moodle/vendor/bin/phpunit "provider_testcase" /home/travis/build/moodle/privacy/tests/provider_test.php
  - /home/travis/build/moodle/vendor/bin/phpunit "tool_dataprivacy_expired_contexts_testcase" /home/travis/build/moodle/admin/tool/dataprivacy/tests/expired_contexts_test.php
  - >
        if [ "$MOODLE_BRANCH" = 'master' ];
        then
            php /home/travis/build/moodle/admin/tool/behat/cli/init.php -a="classic"
            moodle-plugin-ci behat --suite="classic"
        fi

after_success:
  - moodle-plugin-ci coveralls-upload
