name: Automated code checks

on: [push, pull_request]

jobs:
  test:
    name: Automated code checks
    runs-on: ubuntu-22.04

    services:
      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
          MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"

        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0']

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: plugin

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: max_input_vars=5000
          coverage: none

      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV

      - name: Install moodle-plugin-ci
        run: |
          moodle-plugin-ci add-plugin maths/moodle-qbehaviour_adaptivemultipart
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: mariadb
          MOODLE_BRANCH: 'master'

      - name: PHP Lint
        if: ${{ always() }}
        run: moodle-plugin-ci phplint

      #- name: PHP Copy/Paste Detector
      #  continue-on-error: true
      #  if: ${{ always() }}
      #  run: moodle-plugin-ci phpcpd

      #- name: Moodle Code Checker
      #  continue-on-error: true
      #  if: ${{ always() }}
      #  run: moodle-plugin-ci codechecker --max-warnings 0

      #- name: Moodle PHPDoc Checker
      #  continue-on-error: true
      #  if: ${{ always() }}
      #  run: moodle-plugin-ci phpdoc

      - name: Validating
        if: ${{ always() }}
        run: moodle-plugin-ci validate

      - name: Check upgrade savepoints
        if: ${{ always() }}
        run: moodle-plugin-ci savepoints

      - name: Mustache Lint
        if: ${{ always() }}
        run: moodle-plugin-ci mustache

      - name: Grunt
        continue-on-error: true
        if: ${{ always() }}
        run: moodle-plugin-ci grunt --max-lint-warnings 0
